### ISSUE TITLE
Positioned to the right

### ISSUE THREAD

**Issue by divan** [obscuredetour/simply-nav#2]
Hey, thanks for wonderful library.

How hard will it be to add support for the right side menu? I.e. Icon should be on the right, and list appearing from the right?

(Another option I would love to have is to have full width menu – good for very small screen, but that's probably another request)

**Comment by obscuredetour** [comment]
Hey @divan, 

Glad you're finding use for the library. I will look into adding right side functionality as well as a full width menu option. Look for this in a near future release.

**Comment by obscuredetour** [comment]
This has now been implemented! Please see README for more info.
